// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: credprovider.proto

package credproviderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecretRequestContext is the attested context Substrate passes with a request.
// The provider is trusted to have authenticated the caller (mutual TLS); the
// caller is trusted to have attested the actor identity.
type SecretRequestContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The attested actor identity on whose behalf the secret is fetched. Today
	// this is the actor's SPIFFE URI as verified by the egress gateway; a
	// verifiable Actor JWT is the intended future form.
	ActorIdentity string `protobuf:"bytes,1,opt,name=actor_identity,json=actorIdentity,proto3" json:"actor_identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretRequestContext) Reset() {
	*x = SecretRequestContext{}
	mi := &file_credprovider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretRequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretRequestContext) ProtoMessage() {}

func (x *SecretRequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_credprovider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretRequestContext.ProtoReflect.Descriptor instead.
func (*SecretRequestContext) Descriptor() ([]byte, []int) {
	return file_credprovider_proto_rawDescGZIP(), []int{0}
}

func (x *SecretRequestContext) GetActorIdentity() string {
	if x != nil {
		return x.ActorIdentity
	}
	return ""
}

// RequestSecretRequest asks a provider to resolve one credential URI.
type RequestSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A substrate-secret:// URI:
	//   substrate-secret://<provider class>/<provider name>/<provider tail>
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// The attested context for the request.
	Context       *SecretRequestContext `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSecretRequest) Reset() {
	*x = RequestSecretRequest{}
	mi := &file_credprovider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSecretRequest) ProtoMessage() {}

func (x *RequestSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credprovider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSecretRequest.ProtoReflect.Descriptor instead.
func (*RequestSecretRequest) Descriptor() ([]byte, []int) {
	return file_credprovider_proto_rawDescGZIP(), []int{1}
}

func (x *RequestSecretRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *RequestSecretRequest) GetContext() *SecretRequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// RequestSecretResponse carries the resolved secret material.
type RequestSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw secret bytes. The caller decides how to use them (e.g. as a bearer
	// token); the provider does not format them.
	Secret        []byte `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSecretResponse) Reset() {
	*x = RequestSecretResponse{}
	mi := &file_credprovider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSecretResponse) ProtoMessage() {}

func (x *RequestSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credprovider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSecretResponse.ProtoReflect.Descriptor instead.
func (*RequestSecretResponse) Descriptor() ([]byte, []int) {
	return file_credprovider_proto_rawDescGZIP(), []int{2}
}

func (x *RequestSecretResponse) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

var File_credprovider_proto protoreflect.FileDescriptor

const file_credprovider_proto_rawDesc = "" +
	"\n" +
	"\x12credprovider.proto\x12\fcredprovider\"=\n" +
	"\x14SecretRequestContext\x12%\n" +
	"\x0eactor_identity\x18\x01 \x01(\tR\ractorIdentity\"f\n" +
	"\x14RequestSecretRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12<\n" +
	"\acontext\x18\x02 \x01(\v2\".credprovider.SecretRequestContextR\acontext\"/\n" +
	"\x15RequestSecretResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\fR\x06secret2p\n" +
	"\x12CredentialProvider\x12Z\n" +
	"\rRequestSecret\x12\".credprovider.RequestSecretRequest\x1a#.credprovider.RequestSecretResponse\"\x00B?Z=github.com/agent-substrate/substrate/pkg/proto/credproviderpbb\x06proto3"

var (
	file_credprovider_proto_rawDescOnce sync.Once
	file_credprovider_proto_rawDescData []byte
)

func file_credprovider_proto_rawDescGZIP() []byte {
	file_credprovider_proto_rawDescOnce.Do(func() {
		file_credprovider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credprovider_proto_rawDesc), len(file_credprovider_proto_rawDesc)))
	})
	return file_credprovider_proto_rawDescData
}

var file_credprovider_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_credprovider_proto_goTypes = []any{
	(*SecretRequestContext)(nil),  // 0: credprovider.SecretRequestContext
	(*RequestSecretRequest)(nil),  // 1: credprovider.RequestSecretRequest
	(*RequestSecretResponse)(nil), // 2: credprovider.RequestSecretResponse
}
var file_credprovider_proto_depIdxs = []int32{
	0, // 0: credprovider.RequestSecretRequest.context:type_name -> credprovider.SecretRequestContext
	1, // 1: credprovider.CredentialProvider.RequestSecret:input_type -> credprovider.RequestSecretRequest
	2, // 2: credprovider.CredentialProvider.RequestSecret:output_type -> credprovider.RequestSecretResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_credprovider_proto_init() }
func file_credprovider_proto_init() {
	if File_credprovider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credprovider_proto_rawDesc), len(file_credprovider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credprovider_proto_goTypes,
		DependencyIndexes: file_credprovider_proto_depIdxs,
		MessageInfos:      file_credprovider_proto_msgTypes,
	}.Build()
	File_credprovider_proto = out.File
	file_credprovider_proto_goTypes = nil
	file_credprovider_proto_depIdxs = nil
}
